project:
  type: default
  output-dir: docs
  render:
    - index.qmd
    - gca_simulation.qmd
    - gca_calculation.qmd
    - multilocation_alpha_lattice.qmd
    - diallel_gca_sca_analysis.qmd
    - iris_anova_cld.qmd
