#!/usr/bin/env Rscript
# report_callrate_repavg.R -- do CallRate / RepAvg explain the unlinked junctions?
#
# Reproduces what dartR's gl.report.callrate / gl.report.reproducibility do -- show the
# DISTRIBUTION and the retained counts across candidate thresholds, so a threshold is
# chosen from the data instead of asserted. (dartR is not installed here.)
#
# WHAT THE METRICS ARE
#   CallRate -- fraction of samples with a non-missing call at that marker. VERIFIED:
#               recomputed called/186 matches DArT's column to 4.95e-07 across all
#               5,208 markers (verify_dart_codes.R).
#   RepAvg   -- per dartR: "generated by reproducing the data independently for 30[%]
#               of alleles that give a repeatable result, averaged over both alleles for
#               each locus." So it is DArT's OWN technical-replicate repeatability per
#               locus -- not computable from our 186 samples, which contain no duplicate
#               pairs (max pairwise IBS 0.687).
#
# THE ACTUAL QUESTION: round 1 saturates ~476 junctions at rf = 0.5 (est.map's 1001.506
# cM ceiling). Are the markers responsible concentrated in the low tail of these two
# metrics? If yes, they are the right filters and I was wrong to drop them. If no, they
# are not the explanation and a threshold on them is just marker attrition.
#
# I previously set RepAvg >= 0.95 as a round number in the first hour -- 839 markers,
# the second-largest cut in the pipeline -- without looking up what the column meant.
#
# READ-ONLY.
# Usage: Rscript scripts/qtl/report_callrate_repavg.R > agent/report_callrate_repavg.log 2>&1

suppressMessages({library(qtl); library(data.table)})
rule <- function(x) cat("\n", strrep("=", 70), "\n", x, "\n", strrep("=", 70), "\n", sep = "")
D <- "data/qtl/derived"

d <- fread("data/qtl/Report_DMz26-3123_SNP_mapping_2.csv", skip = 6, header = TRUE)
qual <- d[, .(marker = AlleleID, CallRate, RepAvg)]
cr <- read.cross(format = "csvsr", dir = "",
                 genfile = file.path(D, "rqtl_gen_abh_all.csv"),
                 phefile = file.path(D, "rqtl_phe.csv"),
                 genotypes = c("A","H","B"), na.strings = c("-","NA"),
                 crosstype = "f2", estimate.map = FALSE)
G <- pull.geno(cr); chrv <- rep(names(cr$geno), nmar(cr)); dose <- G - 1L
mk <- data.table(marker = colnames(dose), chr = chrv)
mk <- merge(mk, qual, by = "marker", all.x = TRUE)
setkey(mk, marker)
cat("markers in the encoded set:", nrow(mk), " individuals:", nrow(dose), "\n")

rule("1. DISTRIBUTIONS (what gl.report.* shows you)")
for (v in c("CallRate", "RepAvg")) {
  cat("\n", v, ":\n", sep = "")
  print(round(quantile(mk[[v]], c(0,.01,.05,.10,.25,.50,.75,.90,1), na.rm = TRUE), 4))
}

rule("2. RETAINED COUNTS ACROSS CANDIDATE THRESHOLDS")
cat("CallRate:\n")
for (t in c(0.50, 0.60, 0.70, 0.80, 0.90, 0.95))
  cat(sprintf("  >= %.2f : retain %4d  drop %4d (%.1f%%)\n", t,
              mk[CallRate >= t, .N], mk[CallRate < t, .N],
              100*mk[CallRate < t, .N]/nrow(mk)))
cat("\nRepAvg:\n")
for (t in c(0.90, 0.92, 0.94, 0.95, 0.96, 0.98, 1.00))
  cat(sprintf("  >= %.2f : retain %4d  drop %4d (%.1f%%)\n", t,
              mk[RepAvg >= t, .N], mk[RepAvg < t, .N],
              100*mk[RepAvg < t, .N]/nrow(mk)))

rule("3. IDENTIFY THE UNLINKED MARKERS (the rf = 0.5 offenders)")
# A marker is an offender if it fails to correlate with ANY physical neighbour.
K <- 5L
absmax <- rep(NA_real_, ncol(dose))
for (ch in unique(chrv)) {
  idx <- which(chrv == ch); n <- length(idx); dd <- dose[, idx, drop = FALSE]
  for (k in seq_len(n)) {
    nb <- setdiff(max(1,k-K):min(n,k+K), k)
    cs <- sapply(nb, function(j) {
      a <- dd[,k]; b <- dd[,j]; ok <- is.finite(a) & is.finite(b)
      if (sum(ok) < 30) return(NA_real_); abs(cor(a[ok], b[ok]))
    })
    if (!all(is.na(cs))) absmax[idx[k]] <- max(cs, na.rm = TRUE)
  }
}
mk[, absmax := absmax[match(marker, colnames(dose))]]
mk[, offender := is.finite(absmax) & absmax < 0.30]
cat("markers correlating with NO neighbour (|cor| < 0.30):", mk[offender == TRUE, .N],
    sprintf("(%.1f%%)\n", 100*mean(mk$offender, na.rm = TRUE)))

rule("4. DO THE METRICS EXPLAIN THEM?")
cat("offenders vs sound, on both metrics:\n")
print(mk[!is.na(offender), .(n = .N,
        median_CallRate = round(median(CallRate, na.rm=TRUE), 4),
        median_RepAvg   = round(median(RepAvg, na.rm=TRUE), 4),
        pct_CallRate_lt_0.90 = round(100*mean(CallRate < 0.90, na.rm=TRUE), 1),
        pct_RepAvg_lt_0.95   = round(100*mean(RepAvg < 0.95, na.rm=TRUE), 1)),
    by = offender])

cat("\nENRICHMENT -- offender rate within each metric band:\n")
mk[, cr_band := cut(CallRate, c(0,.5,.7,.8,.9,.95,1), include.lowest = TRUE)]
print(mk[!is.na(offender), .(n = .N, offenders = sum(offender),
        pct = round(100*mean(offender), 1)), by = cr_band][order(cr_band)])
mk[, ra_band := cut(RepAvg, c(0,.90,.94,.96,.98,1), include.lowest = TRUE)]
print(mk[!is.na(offender), .(n = .N, offenders = sum(offender),
        pct = round(100*mean(offender), 1)), by = ra_band][order(ra_band)])

rule("5. HOW MANY OFFENDERS WOULD EACH THRESHOLD REMOVE?")
nof <- mk[offender == TRUE, .N]
cat(sprintf("total offenders: %d\n\n", nof))
cat("CallRate threshold:  offenders removed / sound markers sacrificed\n")
for (t in c(0.50, 0.60, 0.70, 0.80, 0.90, 0.95))
  cat(sprintf("  >= %.2f : %4d/%d offenders (%.0f%%)   %4d sound lost\n", t,
              mk[offender == TRUE & CallRate < t, .N], nof,
              100*mk[offender == TRUE & CallRate < t, .N]/nof,
              mk[offender == FALSE & CallRate < t, .N]))
cat("\nRepAvg threshold:\n")
for (t in c(0.90, 0.94, 0.95, 0.96, 0.98))
  cat(sprintf("  >= %.2f : %4d/%d offenders (%.0f%%)   %4d sound lost\n", t,
              mk[offender == TRUE & RepAvg < t, .N], nof,
              100*mk[offender == TRUE & RepAvg < t, .N]/nof,
              mk[offender == FALSE & RepAvg < t, .N]))

rule("VERDICT")
cat("Read section 4: if the offender rate rises steeply toward the low bands, these\n")
cat("metrics DO explain the unlinked junctions and are the right filters. If the rate\n")
cat("is flat across bands, they do not, and thresholding them is just attrition --\n")
cat("in which case the offenders are something else (paralogous tags, wrong CML530\n")
cat("calls) and need a different handle.\n")
